// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  // Defining Amplify Project Region AWS
  aws_project_region: "ap-southeast-1",

  // AWS Cognito Identity Pool ID
  aws_cognito_identity_pool_id:
    "ap-southeast-1:992b203b-d253-4480-8cb5-329f621d9cec",

  // AWS Cognito Region
  aws_cognito_region: "ap-southeast-1",

  // AWS Cognito User Pool ID
  aws_user_pools_id: "ap-southeast-1_Tf3c7Cup9",

  // AWS Cognito Web Client Pool for Mobile
  aws_user_pools_web_client_id: "4vu8c84mte0tdbphe1ol00t55",

  // Hosted UI Config
  oauth: {},
  aws_content_delivery_bucket:
    "react-amplify-20200427173518-hostingbucket-reactjs",
  aws_content_delivery_bucket_region: "ap-southeast-1",
  aws_content_delivery_url:
    "http://react-amplify-20200427173518-hostingbucket-reactjs.s3-website-ap-southeast-1.amazonaws.com",
};

export default awsmobile;
